apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddd-backend-worker-generalpurpose
  labels:
    app: phpfpm-worker-generalpurpose
    version: "097f29a"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpfpm-worker-generalpurpose
  template:
    metadata:
      labels:
        app: phpfpm-worker-generalpurpose
    spec:
      containers:
        - name: phpfpm-worker-generalpurpose
          image: registry.digitalocean.com/ddd/ddd-backend-php:097f29a
          command: ["/bin/sh", "-c"]
          args:
            ["-c", "php artisan consumers:work --topic=general.purpose;"]
          ports:
            - containerPort: 9000
              name: php
          envFrom:
            - secretRef:
                name: phpfpm-env
