apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddd-backend-worker-emailnotifications
  labels:
    app: phpfpm-worker-emailnotifications
    version: "097f29a"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpfpm-worker-emailnotifications
  template:
    metadata:
      labels:
        app: phpfpm-worker-emailnotifications
    spec:
      containers:
        - name: phpfpm-worker-emailnotifications
          image: registry.digitalocean.com/ddd/ddd-backend-php:097f29a
          command: ["/bin/sh", "-c"]
          args:
            [
              "-c",
              "php artisan consumers:work --topic=ddd.orders.emailnotifications;",
            ]
          ports:
            - containerPort: 9000
              name: php
          envFrom:
            - secretRef:
                name: phpfpm-env