apiVersion: v1
kind: Secret
metadata:
  name: phpfpm-env
data:
  ALLOWED_ORIGIN: aHR0cDovL3d3dy5kZGQuY29t
  API_USER_ADMIN: ""
  API_USER_ADMIN_PASSWORD: ""
  API_USER_TOKEN_TTL_IN_MINUTES: ""
  APP_DEBUG: dHJ1ZQo=
  APP_ENV: bG9jYWw=
  APP_KEY: Yzc0ZmY1ZWY5ZGNmOWJjNzFjOWRlZTYySYjU=
  APP_NAME: TW92ZW91dA==
  APP_TIMEZONE: VVRD
  APP_URL: aHR0cL2saG9zdA==
  CACHE_DRIVER: cmVkaXM=
  COMPOSER_AUTH: eyJnaXRodsa23dpdGh1YlQaEtieGtURTdYZGwyT0xpcmtpRVVrR1ZXNzBlWEdHbyJ9fQo=
  CLOSE_API: aHR0cHM6Ly9hcGkuY2xvc2FwaS92MS8=
  CLOSE_API_KEY: YXBpXzVMNXV6eDNFWTRbDIuM0ppMW1jMHpYbG15OVB4NllyQUJJTzo=
  CLOSE_USER_TYPE_FIELD: Y3VzdG9tLmNmXA4elhFdUhGMDRiRmxUTlduN0FSYkpjUjh5ZGVFRzZrUXlSOGo=
  CLOSE_USER_ID_FIELD: Y3VzdG9tLmNmX04RVA5dThoZ2Vhb1R5UW5yOFV3aFhQQjBPWDlsc25idmRqZEQ=
  CLOSE_ORDER_CREATED_FIELD: Y3VzdG9tLmNmX0l5NTV1FyOVJxY3lhWUFtNjlnUmhabUVCV0o=
  CLOSE_ORDER_CONFIRMED_FIELD: Y3VzdG9tLmNmX2U2xUaVp6TTF4cGw5M2tuVU9CQjlUdk5iZUk1eHI=
  CLOSE_CLEANING_SCHEDULED_FIELD: Y3VzdG9tLmNmX2dazJsNjNUVGEydXBuRGJobXlYcTFrTDBPMjI=
  CLOSE_CLEANING_ACCEPTED_FIELD: Y3VzdG9tLmDfX2dQazJsNjNUVGEydXBuRGJobXlYcTFrTDBPMjI=
  CLOSE_CLEANING_STARTED_FIELD: Y3VzdG9tLmptRWdqYXVhbW43bVYzUDVIWWVDWUIyNEtFeGF6dHpUc0thT1E=
  CLOSE_CLEANING_COMPLETED_FIELD: Y3VzdG9tLmNmX2wwp2SkJoTDRESmU4S0FROUdMRXZnclFrSXhZNXo=
  CLOSE_CLEANING_CANCELED_TYPE_FIELD: Y3VzdG9tLmN5FZ3VTeHE2bzFyOWhtWE82dEo=
  CLOSE_CLEANING_RESCHEDULED: Y3VzdG9tLmNmX0pua25Z3M4ZEJYdUJJNFdDNHc=
  DB_CONNECTION: bXlzcWw=
  DB_DATABASE: bW92ZW91dA==
  DB_HOST: bXlzcWwuZGF0YWJhc2Uuc3ZjLmNsdXN0ZXIubG9jYWw=
  DB_PASSWORD:
  DB_PORT: MzMwNg==
  DB_USERNAME: cm9vdA==
  KAFKA_BROKER_SERVERS: a2Fma2Eua2Fma2Euc3ZjWw6OTA5MixrYWZrYS0wLmthZmthLWhlYWRsZXNzLmthZmthLnN2Yy5jbHVzdGVyLmxvY2FsOjkwOTI=
  KAFKA_GROUP_ID_DEFAULT: bW92ZW91dF9kZWZSSShdWx0X2dyb3Vw
  KAFKA_SASL_PASSWORD:
  KAFKA_SASL_USERNAME:
  LINKMINK_LIVEMODE:
  LINKMINK_TYPE:
  LINKMINK_STATUS:
  LINKMINK_API:
  LINKMINK_PRIVATE_LIVE_API_KEY:
  LOG_CHANNEL: c3RhY2sK
  LOG_SLACK_WEBHOOK_URL: ""
  MAIL_ENCRYPTION: dGxz
  MAIL_FROM_ADDRESS: 
  MAIL_FROM_NAME: 
  MAIL_HOST: 
  MAIL_MAILER: c2Vz
  MAIL_PASSWORD:
  MAIL_PORT: MjUyNQ==
  MAIL_USERNAME: ssswq=
  MAIL_AWS_SES_ACCESS_KEY_ID:
  MAIL_AWS_SES_SECRET_ACCESS_KEY:
  MAIL_AWS_SES_DEFAULT_REGION:
  QUEUE_CONNECTION: c3luYw==
  REDIS_CLIENT: cHJlZGlz
  REDIS_HOST: cmVkaXMtbWFzdGVyLnJlZGlzLnN2Yy5jbHVzdGVyLmxvY2Fs
  REDIS_PASSWORD:
  REDIS_PORT: NjM3OQ==
  SLACK_ORDER_WEBHOOK_URL: ""
  EXTERNALPARTNER_API: sdddd=
  EXTERNALPARTNER_CLIENT_ID: Mw==
  EXTERNALPARTNER_CLIENT_SECRET:
  TWILIO_ACCOUNT_SID:
  TWILIO_AUTH_TOKEN:
  TWILIO_SENDER: KzE3NzU1MjI1MjEx
  KAFKA_DLQ_SLACK_WEBHOOK_URL: aHR0cHM6Ly9ob29rcy5ssssbGFjay5jb20vc2Vydmlj0tGL0IwMztWeXRMcW94ZXNmAs22MzRpNVpKdw==
  LOG_SLACK_USERNAME: TW92ZW91dA==
  NOTIFICATIONS_MAGIC_LINK: sdff4fgghh3
  RATE_LIMIT_PER_MINUTE: NTAw
  STRIPE_API_KEY:
  MIXPANEL_TOKEN:
