apiVersion: v1
kind: Service
metadata:
  name: ddd-backend
  labels:
    app: phpfpm
    version: "d4b6446"
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: phpfpm
  type: ClusterIP
  