{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: {{ include "common.capabilities.networkPolicy.apiVersion" . }}
metadata:
  name: {{ printf "%s-ingress" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
    {{- include "common.labels.matchLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    # Allow client connections
    - ports:
        - port: {{ .Values.service.port }}
      {{- if not .Values.networkPolicy.allowExternal }}
      from:
        - podSelector:
            matchLabels:
              {{ template "common.names.fullname" . }}-client: "true"
          {{- if .Values.networkPolicy.explicitNamespacesSelector }}
          namespaceSelector:
{{ toYaml .Values.networkPolicy.explicitNamespacesSelector | indent 12 }}
          {{- end }}
      {{- end }}
    # Allow communication inter-broker
    - ports:
        - port: {{ .Values.service.internalPort }}
      from:
        - podSelector:
            matchLabels:
            {{- include "common.labels.matchLabels" . | nindent 14 }}
    # Allow External connection
    {{- if .Values.externalAccess.enabled }}
    - ports:
        - port: {{ .Values.service.externalPort }}
    {{- if .Values.externalAccess.from }}
      from: {{- include "common.tplvalues.render" ( dict "value" .Values.networkPolicy.externalAccess.from "context" $ ) | nindent 8 }}
    {{- end }}
    {{- end }}
    {{- if .Values.metrics.kafka.enabled }}
    # Allow prometheus scrapes
    - ports:
        - port: {{ .Values.metrics.kafka.service.port }}
    {{- end }}
{{- end }}
